### PR TITLE
Enable more MailTo options on Android

### PR DESCRIPTION
**Pull request by Depechie**

### CODE REVIEW

**Comment by SKLn-Rad** [comment]
Didn't notice you merged into my develop branch! Will merge onto master.

**Comment by Depechie** [comment]
Wasn't that the way to go? Or was Develop not maintained?

**Comment by Depechie** [comment]
Don't need the nuget right away no :)

**Comment by SKLn-Rad** [comment]
Nah develop is fine. I generally merge them every release and do all my work on Dev anyway! Going to try and get macos working tonight so and an incremental release

**Pull request merged**
